### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by pham-dat** [lemonwaysas/prestashop-webkul-lemonway-plugin#1]
![1](https://cloud.githubusercontent.com/assets/13848893/16416108/ec9b7e84-3d40-11e6-9271-c81e70b35d1e.PNG)

@sirateck 
Dans la configuration du plugin, ça correspond à quoi ces champs de commissions ?

**Comment by sirateck** [comment]
@Crocodile29292 ,

C'est la commission prélevée lors d'un moneyout par le vendeur.
