### ISSUE TITLE
Erreur Front office Lemonway

### ISSUE THREAD

**Issue by w3houde** [lemonwaysas/prestashop-webkul-lemonway-plugin#4]
Bonjour, après installation et configuration de l'environnement de dev j'ai une erreur : {prestashop_location}/modules/lemonwaymkt/controllers/front/wallet.php on line 185 

Pouvez vous m'indiquer la démarche à suivre pour corriger le bug? 

Je suis sur Prestashop 1.6.1.11

Merci d'avance,

Hello i've setup and deploy the dev server and i've the following error : {prestashop_location}/modules/lemonwaymkt/controllers/front/wallet.php on line 185 

Can you help me for fix this bug?

I'm on Prestashop 1.6.1.11 

Best regards,

**Comment by pham-dat** [comment]
Bonjour,

Quelle version de Webkul Marketplace avez-vous ?
Notre module n'est pas compatible avec Webkul Marketplace 2.1.
Veuillez contacter Webkul pour demander la version 2.0.
